export const COLOUR = {
  PRIMARY: '#22C7FC',
  SECONDARY: '#4C68A3',
  GREY_ONE: '#313B4C',
  GREY_TWO: '#4A4A4A',
  GREY_THREE: '#EEEEEE',
  GREY_FOUR: '#E7EBEF',
  GREY_FIVE: '#F5F7F8',
  WHITE: '#FFFFFF',
};
