const SECONDS_PER_MINUTE = 60;

const ONE_SECOND = 1000;
const ONE_MINUTE = SECONDS_PER_MINUTE * ONE_SECOND;
const TEN_MINUTES = ONE_MINUTE * 10;
const THIRTY_MINUTES = TEN_MINUTES * 3;

export const MILLISECONDS = {
  ONE_SECOND,
  ONE_MINUTE,
  TEN_MINUTES,
  THIRTY_MINUTES,
};
