export const REDUCER_SHAPE = {
  BLUETOOTH: 'bluetooth',
  PASSIVE_BLUETOOTH: 'passive_bluetooth',
  BLUETOOTH_STATE: 'bluetooth_state',
  SENSORS: 'sensors',
  TEMPERATURE_LOGS: 'temperature_logs',
  SENSOR: 'sensor',
  SETTING: 'setting',
  BREACH_CONFIGURATION: 'breach_configuration',
  TEMPERATURE_LOG: 'temperature_log',
  HYDRATE: 'hydrate',
  CHART: 'chart',
  BREACH: 'breach',
  DEVICE: 'device',
  LOG_TABLE: 'log_table',
  TEMPERATURE_DOWNLOAD: 'temperature_download',
};
