export const SERVICES = {
  BLUETOOTH: 'bluetooth',
  DATABASE: 'database',
  DEVICE: 'device',
  DATABASE_UTILS: 'databaseUtils',
};

export const BLUETOOTH_SERVICE = {
  MAX_INTERVAL: 20864,
  MIN_INTERVAL: 60,
  DEFAULT_INTERVAL: 300,
  DEFAULT_MANUFACTURER_ID: 307,
  DEFAULT_PASSIVE_DOWNLOAD_DELAY: 10000,
  DEFAULT_TIMER_DELAY: 5000,
};
