export const SETTING = {
  INT: {
    DEFAULT_LOG_INTERVAL: 'DEFAULT_LOG_INTERVAL',
    DOWNLOAD_INTERVAL: 'DOWNLOAD_INTERVAL',
  },
  BOOL: {
    AUTO_APPLY_BREACH_CONFIGS: 'AUTO_APPLY_BREACH_CONFIGS',
  },
};
