export const STYLE = {
  BORDER: {
    RADIUS: {
      NORMAL: 37.5,
      CIRCLE: 50,
      RECTANGLE: 5.33,
    },
    WIDTH: {
      NORMAL: 2,
    },
  },
  WIDTH: {
    NORMAL_BUTTON: 200,
    CIRCLE_BUTTON: 87,
    HALF_CIRCLE: 30,
    LARGE_RECTANGLE: 180,
    NORMAL_CHART: 500,
    SETTINGS_ICON: 50,
    TEXT_INPUT: 200,
    DIVIDER_FULL: '100%',
    DIVIDER_NEARLY_FULL: '90%',
  },
  HEIGHT: {
    NORMAL_BUTTON: 60,
    CIRCLE_BUTTON: 86,
    HALF_CIRCLE: 60,
    LARGE_RECTANGLE: 60,
    NORMAL_CHART: 240,
    SENSOR_ROW: 250,
    SETTINGS_ITEM: 100,
    SUB_TEXT: 10,
    SETTINGS_EDIT_MODAL: 500,
    SETTINGS_EDIT_BUTTON: 100,
    SETTINGS_EDIT_CONTENT_AREA: 75,
    PICKER: 50,
  },
  PADDING: {
    HORIZONTAL: 50,
    VERTICAL: 50,
  },
  ICON: {
    SIZE: {
      L: 60,
      S: 20,
    },
  },
};
