export enum DEPENDENCY {
  MIGRATION = 'migrationService',
  LOCATOR = 'DependencyLocator',
  BLUETOOTH = 'bluetooth',
  DATABASE = 'database',
  DEVICE = 'device',
  EXPORT_SERVICE = 'exportService',
  FORMAT_SERVICE = 'formatService',
  UTIL_SERVICE = 'utilService',
  DATABASE_UTILS = 'databaseUtils',
  SENSOR_MANAGER = 'sensorManager',
  TEMPERATURE_LOG_MANAGER = 'temperatureLogManager',
  SETTING_MANAGER = 'settingManager',
  BREACH_CONFIGURATION_MANAGER = 'breachConfigurationManager',
  CHART_MANAGER = 'chartManager',
  BREACH_MANAGER = 'breachManager',
  LOG_TABLE_MANAGER = 'logTableManager',
  DEV_MANAGER = 'devManager',
  DOWNLOAD_MANAGER = 'downloadManager',
  REPORT_MANAGER = 'reportManager',
  PERMISSION_SERVICE = 'permissionService',
  SENSOR_STATUS_MANAGER = 'sensorStatusManager',
  CONSECUTIVE_BREACH_MANAGER = 'consecutiveBreachManager',
  CUMULATIVE_BREACH_MANAGER = 'cumulativeBreachManager',
  ACKNOWLEDGE_BREACH_MANAGER = 'acknowledgeBreachManager',
  LOGGER_SERVICE = 'loggerService',
  SYNC_SERVICE = 'syncService',
  SYNC_QUEUE_MANAGER = 'syncQueueManager',
  SYNC_OUT_MANAGER = 'syncOutManager',
}

export const BLUETOOTH_SERVICE = {
  MAX_INTERVAL: 20864,
  MIN_INTERVAL: 60,
  DEFAULT_INTERVAL: 300,
  DEFAULT_MANUFACTURER_ID: 307,
  DEFAULT_PASSIVE_DOWNLOAD_DELAY: 10000,
  DEFAULT_TIMER_DELAY: 5000,
};
