const SECONDS_PER_MINUTE = 60;
const MINUTES_PER_HOUR = 60;
const HOURS_PER_DAY = 24;

const ONE_SECOND = 1000;
const ONE_MINUTE = SECONDS_PER_MINUTE * ONE_SECOND;
const ONE_HOUR = ONE_MINUTE * MINUTES_PER_HOUR;
const ONE_DAY = ONE_HOUR * HOURS_PER_DAY;

const TEN_SECONDS = ONE_SECOND * 10;
const TEN_MINUTES = ONE_MINUTE * 10;
const THIRTY_MINUTES = TEN_MINUTES * 3;

export const MILLISECONDS = {
  ONE_SECOND,
  ONE_MINUTE,
  TEN_SECONDS,
  TEN_MINUTES,
  THIRTY_MINUTES,
  ONE_DAY,
};
