export const REDUCER = {
  DATABASE: 'database',
  BLUETOOTH: 'bluetooth',
  SENSORS: 'sensors',
  TEMPERATURE_LOGS: 'temperatureLogs',
  SENSOR: 'sensor',
  SETTING: 'setting',
  BREACH_CONFIGURATION: 'breachConfiguration',
  TEMPERATURE_LOG: 'temperatureLog',
  CHART: 'chart',
  BREACH: 'breach',
  DEVICE: 'device',
  LOG_TABLE: 'logTable',
  UPDATE: 'update',
  SCAN: 'scan',
  DOWNLOAD: 'download',
  BLINK: 'blink',
  BATTERY_OBSERVER: 'batteryObserver',
  NEW_SENSOR: 'new_sensor',
  REPORT: 'report',
  PERMISSION: 'permission',
  SENSOR_STATUS: 'sensorStatus',
};
