export const REDUCER = {
  DATABASE: 'database',
  BLUETOOTH: 'bluetooth',
  SENSORS: 'sensors',
  TEMPERATURE_LOGS: 'temperature_logs',
  SENSOR: 'sensor',
  SETTING: 'setting',
  BREACH_CONFIGURATION: 'breach_configuration',
  TEMPERATURE_LOG: 'temperature_log',
  HYDRATE: 'hydrate',
  CHART: 'chart',
  BREACH: 'breach',
  DEVICE: 'device',
  LOG_TABLE: 'log_table',
  TEMPERATURE_DOWNLOAD: 'temperature_download',
  UPDATE: 'update',
  SCAN: 'scan',
  DOWNLOAD: 'download',
  BLINK: 'blink',
  BATTERY_OBSERVER: 'battery_observer',
  NEW_SENSOR: 'new_sensor',
};
