export const BLUETOOTH_SETTING = {
  DEFAULT_LOG_INTERVAL: 'DEFAULT_LOG_INTERVAL',
};

export const SYNC_SETTING = {
  AUTH_URL: 'AUTH_URL',
  AUTH_USERNAME: 'AUTH_USERNAME',
  AUTH_PASSWORD: 'AUTH_PASSWORD',
  SENSOR_URL: 'SENSOR_URL',
  TEMPERATURE_LOG_URL: 'TEMPERATURE_LOG_URL',
  TEMPERATURE_BREACH_URL: 'TEMPERATURE_BREACH_URL',
  LAST_SYNC: 'LAST_SYNC',
  IS_PASSIVE_SYNC_ENABLED: 'IS_PASSIVE_SYNC_ENABLED',
};

export const SETTING = {
  BLUETOOTH: BLUETOOTH_SETTING,
  SYNC: SYNC_SETTING,
};
